// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { properties, roomTypes, bookings } from "./db_schema";

export const roomTypesRelations = relations(roomTypes, ({one, many}) => ({
	property: one(properties, {
		fields: [roomTypes.propertyId],
		references: [properties.id]
	}),
	bookings: many(bookings),
}));

export const propertiesRelations = relations(properties, ({many}) => ({
	roomTypes: many(roomTypes),
	bookings: many(bookings),
}));

export const bookingsRelations = relations(bookings, ({one}) => ({
	roomType: one(roomTypes, {
		fields: [bookings.roomTypeId],
		references: [roomTypes.id]
	}),
	property: one(properties, {
		fields: [bookings.propertyId],
		references: [properties.id]
	}),
}));