-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE admins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  created_at INTEGER DEFAULT (unixepoch()) NOT NULL
);

CREATE TABLE bookings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  property_id INTEGER NOT NULL REFERENCES properties(id),
  room_type_id INTEGER NOT NULL REFERENCES room_types(id),
  check_in INTEGER NOT NULL,
  check_out INTEGER NOT NULL,
  guests INTEGER NOT NULL DEFAULT 1,
  total_price INTEGER NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'HKD',
  status TEXT NOT NULL DEFAULT 'pending',
  payment_status TEXT NOT NULL DEFAULT 'unpaid',
  payment_method TEXT,
  special_requests TEXT,
  voucher_code TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE inquiries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new',
  admin_reply TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE properties (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  name_zh TEXT NOT NULL,
  description TEXT,
  description_zh TEXT,
  location TEXT,
  price_per_night INTEGER NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'HKD',
  max_guests INTEGER DEFAULT 2,
  image_url TEXT,
  gallery TEXT,
  amenities TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE room_types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  property_id INTEGER NOT NULL REFERENCES properties(id),
  name TEXT NOT NULL,
  name_zh TEXT NOT NULL,
  description TEXT,
  description_zh TEXT,
  price_per_night INTEGER NOT NULL DEFAULT 0,
  max_guests INTEGER DEFAULT 2,
  inventory INTEGER NOT NULL DEFAULT 1,
  image_url TEXT,
  amenities TEXT,
  status TEXT NOT NULL DEFAULT 'available',
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE trip_plans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  destination TEXT,
  start_date INTEGER,
  end_date INTEGER,
  items TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- INDEXS

CREATE UNIQUE INDEX admins_email_idx ON admins(email);

CREATE UNIQUE INDEX admins_user_id_idx ON admins(user_id);

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_bookings_property ON bookings(property_id);

CREATE INDEX idx_bookings_status ON bookings(status);

CREATE INDEX idx_bookings_user ON bookings(user_id);

CREATE INDEX idx_inquiries_status ON inquiries(status);

CREATE INDEX idx_inquiries_user ON inquiries(user_id);

CREATE INDEX idx_properties_status ON properties(status);

CREATE INDEX idx_room_types_property ON room_types(property_id);

CREATE INDEX idx_room_types_status ON room_types(status);

CREATE INDEX idx_trip_plans_user ON trip_plans(user_id);
