// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const properties = sqliteTable("properties", {
	id: integer().primaryKey({ autoIncrement: true }),
	name: text().notNull(),
	nameZh: text("name_zh").notNull(),
	description: text(),
	descriptionZh: text("description_zh"),
	location: text(),
	pricePerNight: integer("price_per_night").default(0).notNull(),
	currency: text().default("HKD").notNull(),
	maxGuests: integer("max_guests").default(2),
	imageUrl: text("image_url"),
	gallery: text(),
	amenities: text(),
	status: text().default("active").notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	index("idx_properties_status").on(table.status),
]);

export const roomTypes = sqliteTable("room_types", {
	id: integer().primaryKey({ autoIncrement: true }),
	propertyId: integer("property_id").notNull().references(() => properties.id),
	name: text().notNull(),
	nameZh: text("name_zh").notNull(),
	description: text(),
	descriptionZh: text("description_zh"),
	pricePerNight: integer("price_per_night").default(0).notNull(),
	maxGuests: integer("max_guests").default(2),
	inventory: integer().default(1).notNull(),
	imageUrl: text("image_url"),
	amenities: text(),
	status: text().default("available").notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	index("idx_room_types_status").on(table.status),
	index("idx_room_types_property").on(table.propertyId),
]);

export const bookings = sqliteTable("bookings", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	propertyId: integer("property_id").notNull().references(() => properties.id),
	roomTypeId: integer("room_type_id").notNull().references(() => roomTypes.id),
	checkIn: integer("check_in").notNull(),
	checkOut: integer("check_out").notNull(),
	guests: integer().default(1).notNull(),
	totalPrice: integer("total_price").default(0).notNull(),
	currency: text().default("HKD").notNull(),
	status: text().default("pending").notNull(),
	paymentStatus: text("payment_status").default("unpaid").notNull(),
	paymentMethod: text("payment_method"),
	specialRequests: text("special_requests"),
	voucherCode: text("voucher_code"),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	index("idx_bookings_property").on(table.propertyId),
	index("idx_bookings_status").on(table.status),
	index("idx_bookings_user").on(table.userId),
]);

export const inquiries = sqliteTable("inquiries", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id"),
	name: text().notNull(),
	email: text().notNull(),
	phone: text(),
	subject: text().notNull(),
	message: text().notNull(),
	status: text().default("new").notNull(),
	adminReply: text("admin_reply"),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	index("idx_inquiries_user").on(table.userId),
	index("idx_inquiries_status").on(table.status),
]);

export const tripPlans = sqliteTable("trip_plans", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	name: text().notNull(),
	destination: text(),
	startDate: integer("start_date"),
	endDate: integer("end_date"),
	items: text(),
	notes: text(),
	status: text().default("draft").notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	index("idx_trip_plans_user").on(table.userId),
]);

export const admins = sqliteTable("admins", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	email: text().notNull(),
	role: text().default("admin").notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	uniqueIndex("admins_email_idx").on(table.email),
	uniqueIndex("admins_user_id_idx").on(table.userId),
]);

